FROM node

RUN mkdir /install

#install dependencies
ADD ./package.json /install
WORKDIR /install
RUN npm install --verbose
ENV NODE_PATH=/install/node_modules

ADD . /ls-backend-cron
WORKDIR /ls-backend-cron


CMD ["npm", "run", "cron"]