version: "3"
services:
  cron:
    build:
      context: .
      dockerfile: ./Dockerfile.cron
    container_name: ls-service-cron
    environment:
      - NOTION_BOOKING_DB_ID=${NOTION_BOOKING_DB_ID}
      - NOTION_REPAIR_DB_ID=${NOTION_REPAIR_DB_ID}
      - NOTION_FEEDBACK_DB_ID=${NOTION_FEEDBACK_DB_ID}
      - NOTION_PAGE_ID=${NOTION_PAGE_ID}
      - NOTION_SECRET=${NOTION_SECRET}
      - BOT_TOKEN=${BOT_TOKEN}
      - AWS_KEY_ID=${AWS_KEY_ID}
      - AWS_SECRET=${AWS_SECRET}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - ENV=${ENV}
      - NOTION_BOOKING_DB_ID_DEV=${NOTION_BOOKING_DB_ID_DEV}
      - NOTION_REPAIR_DB_ID_DEV=${NOTION_REPAIR_DB_ID_DEV}
      - NOTION_FEEDBACK_DB_ID_DEV=${NOTION_FEEDBACK_DB_ID_DEV}
      - NOTION_PAGE_ID_DEV=${NOTION_PAGE_ID_DEV}
      - NOTION_SECRET_DEV=${NOTION_SECRET_DEV}
      - BOT_TOKEN_DEV=${BOT_TOKEN_DEV}
      - AWS_KEY_ID_DEV=${AWS_KEY_ID_DEV}
      - AWS_SECRET_DEV=${AWS_SECRET_DEV}
      - AWS_BUCKET_NAME_DEV=${AWS_BUCKET_NAME_DEV}
    volumes:
      - .:/ls-backend-cron #maps current host dir to docker working dir

  web:
    build:
      context: .
      dockerfile: ./Dockerfile.web
    container_name: ls-service-web
    ports:
      - 80:3000
    volumes:
      - .:/ls-backend-web #maps current host dir to docker working dir
      # - /ls-backend-web/node_modules #make node_modules in container persistent
