version: "3"
services:
  cron:
    build:
      context: .
      dockerfile: ./Dockerfile.cron
    container_name: ls-service-cron
    environment:
      - NOTION_BOOKING_DB_ID=${NOTION_BOOKING_DB_ID}
      - NOTION_REPAIR_DB_ID=${NOTION_REPAIR_DB_ID}
      - NOTION_FEEDBACK_DB_ID=${NOTION_FEEDBACK_DB_ID}
      - NOTION_PAGE_ID=${NOTION_PAGE_ID}
      - NOTION_SUBSCRIBER_DB_ID=${NOTION_SUBSCRIBER_DB_ID}
      - NOTION_OTP_DB_ID=${NOTION_OTP_DB_ID}
      - NOTION_COMPANY_DB_ID=${NOTION_COMPANY_DB_ID}
      - NOTION_SECRET=${NOTION_SECRET}
      - BOT_TOKEN=${BOT_TOKEN}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_MESSAGING_SERVICE_SID=${TWILIO_MESSAGING_SERVICE_SID}
      - AWS_KEY_ID=${AWS_KEY_ID}
      - AWS_SECRET=${AWS_SECRET}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - HOSTNAME=${HOSTNAME}
      - ENV=${ENV}
      - NOTION_BOOKING_DB_ID_DEV=${NOTION_BOOKING_DB_ID_DEV}
      - NOTION_REPAIR_DB_ID_DEV=${NOTION_REPAIR_DB_ID_DEV}
      - NOTION_FEEDBACK_DB_ID_DEV=${NOTION_FEEDBACK_DB_ID_DEV}
      - NOTION_PAGE_ID_DEV=${NOTION_PAGE_ID_DEV}
      - NOTION_SUBSCRIBER_DB_ID_DEV=${NOTION_SUBSCRIBER_DB_ID_DEV}
      - NOTION_OTP_DB_ID_DEV=${NOTION_OTP_DB_ID_DEV}
      - NOTION_COMPANY_DB_ID_DEV=${NOTION_COMPANY_DB_ID}
      - NOTION_SECRET_DEV=${NOTION_SECRET_DEV}
      - BOT_TOKEN_DEV=${BOT_TOKEN_DEV}
      - TWILIO_ACCOUNT_SID_DEV=${TWILIO_ACCOUNT_SID_DEV}
      - TWILIO_AUTH_TOKEN_DEV=${TWILIO_AUTH_TOKEN_DEV}
      - TWILIO_MESSAGING_SERVICE_SID_DEV=${TWILIO_MESSAGING_SERVICE_SID_DEV}
      - AWS_KEY_ID_DEV=${AWS_KEY_ID_DEV}
      - AWS_SECRET_DEV=${AWS_SECRET_DEV}
      - AWS_BUCKET_NAME_DEV=${AWS_BUCKET_NAME_DEV}
    volumes:
      - .:/ls-backend-cron #maps current host dir to docker working dir

  web:
    build:
      context: .
      dockerfile: ./Dockerfile.web
    container_name: ls-service-web
    ports:
      - 3000:3000
    volumes:
      - .:/ls-backend-web #maps current host dir to docker working dir
      # - /ls-backend-web/node_modules #make node_modules in container persistent
