#base image
FROM node

RUN mkdir /install

#install dependencies
ADD ./package.json /install
WORKDIR /install
RUN npm install --verbose
ENV NODE_PATH=/install/node_modules

ADD . /ls-backend-web
WORKDIR /ls-backend-web

#RUN
RUN npm install -g nodemon

EXPOSE 3000

CMD ["npm", "run", "dev"]