const RICH_TEXT = 'RICH_TEXT';
const PHONE_NUMBER = 'PHONE_NUMBER';
const NUMBER = 'NUMBER';
const CHECKBOX = 'CHECKBOX';
const SELECT = 'SELECT';
const MULTI_SELECT = 'MULTI_SELECT';
const DATE = 'DATE';
const PEOPLE = 'PEOPLE';
const FILES = 'FILES';
const RELATION = 'RELATION';
const FORMULA = 'FORMULA';
const CREATED_TIME = 'CREATED_TIME';
const LAST_EDITED_TIME = 'LAST_EDITED_TIME';
const EMAIL = 'EMAIL';
const URL = 'URL';
const TITLE = 'TITLE';

module.exports = {
  RICH_TEXT,
  PHONE_NUMBER,
  NUMBER,
  CHECKBOX,
  SELECT,
  MULTI_SELECT,
  DATE,
  PEOPLE,
  FILES,
  RELATION,
  FORMULA,
  CREATED_TIME,
  LAST_EDITED_TIME,
  EMAIL,
  URL,
  TITLE,
};
